# Generated by Django 4.2.16 on 2026-05-26 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('upload_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=20)),
                ('max_files', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_files', models.JSONField(blank=True, default=list)),
                ('allowed_extensions', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.CharField(blank=True, max_length=512)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('upload_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('upload_count', models.PositiveIntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('otp_code_hash', models.CharField(blank=True, max_length=64)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_attempts', models.PositiveIntegerField(default=0)),
                ('otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_sends_hour', models.PositiveIntegerField(default=0)),
                ('otp_hour_window', models.DateTimeField(blank=True, null=True)),
                ('verified_until', models.DateTimeField(blank=True, null=True)),
                ('file_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sharing.filerequest')),
            ],
            options={
                'db_table': 'request_recipients',
                'ordering': ['created_at'],
                'unique_together': {('file_request', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ZipShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('zip_name', models.CharField(default='shared_files.zip', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.CharField(blank=True, max_length=512)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('files', models.ManyToManyField(related_name='zip_shares', to='files.file')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zip_shares',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['shared_by', 'status'], name='zip_shares_shared__ed93c5_idx'), models.Index(fields=['share_token'], name='zip_shares_share_t_85d081_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('file_request', 'File Request'), ('direct_share', 'Direct Share Link Upload'), ('anonymous', 'Anonymous Upload')], max_length=30)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('submitter_name', models.CharField(blank=True, max_length=255)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_action', 'Needs Action'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, max_length=1000)),
                ('rejection_reason', models.TextField(blank=True, max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_to_storage', models.BooleanField(default=False)),
                ('saved_filename', models.CharField(blank=True, default='', max_length=500)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_entry', to='files.file')),
                ('file_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='sharing.filerequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_submissions', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='sharing.requestrecipient')),
            ],
            options={
                'db_table': 'submission_inbox',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='submission__owner_i_13b6f9_idx'), models.Index(fields=['owner', 'source_type'], name='submission__owner_i_b86a43_idx'), models.Index(fields=['file_request', 'status'], name='submission__file_re_a4ca08_idx'), models.Index(fields=['recipient', 'status'], name='submission__recipie_2fc063_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShareAnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sharing.fileshare')),
            ],
            options={
                'db_table': 'share_analytics_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['share', 'event_type'], name='share_analy_share_i_9d2f00_idx'), models.Index(fields=['occurred_at'], name='share_analy_occurre_de89ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['shared_by', 'status'], name='file_shares_shared__6daecd_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['share_token'], name='file_shares_share_t_68bcb5_idx'),
        ),
    ]
