# Generated by Django 4.2.16 on 2026-05-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissioninbox',
            name='saved_filename',
        ),
        migrations.RemoveField(
            model_name='submissioninbox',
            name='saved_to_storage',
        ),
    ]
