# Generated by Django 4.2.16 on 2026-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_remove_submissioninbox_saved_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioninbox',
            name='saved_filename',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='submissioninbox',
            name='saved_to_storage',
            field=models.BooleanField(default=False),
        ),
    ]
