# Generated by Django 4.2.16 on 2026-05-19 06:19

import apps.files.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.files.models.user_upload_path)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('safe', 'Safe'), ('infected', 'Infected'), ('scan_failed', 'Scan Failed')], db_index=True, default='pending', max_length=20)),
                ('scan_result', models.CharField(blank=True, max_length=1000)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiry. Null = never expires automatically.', null=True)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(default='fa-folder', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.ManyToManyField(blank=True, related_name='folders', to='files.file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner'], name='folders_owner_i_b7b606_idx')],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'is_deleted'], name='files_owner_i_42e4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'is_favorite'], name='files_owner_i_56991e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['sha256'], name='files_sha256_150e02_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['scan_status'], name='files_scan_st_a0358a_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['expires_at', 'is_deleted'], name='files_expires_be37b3_idx'),
        ),
    ]
